name: weekly_delivery

on:
  push:
  workflow_dispatch:
    inputs:
      an_input:
        description: "Input?"
jobs:
  Environment:
    runs-on: ubuntu-latest
    env:
      DEFAULT_INPUT: defaultINPUT
    outputs:
      canRunJob: ${{ steps.step1.outputs.canRunJob }}
    steps:
      - id: step1
        run: echo "::set-output name=canRunJob::${{ github.event.inputs.an_input || env.DEFAULT_INPUT }}"

  Test2:
    if: ${{ jobs.Environment.outputs.canRunJob == 'defaultINPUT' }}
    needs: Environment
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo ${{ needs.Environment.outputs.canRunJob }}
