name: test_input

on:
  push:
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
      an_input:
        description: "Input?"
jobs:
  Environment:
    runs-on: ubuntu-latest
    env:
      DEFAULT_INPUT: defaultINPUT
      FLAG: true
    outputs:
      canRunJob: ${{ steps.step1.outputs.canRunJob }}
    steps:
      - id: step1
        run: echo "::set-output name=canRunJob::${{ github.event.inputs.flag != false && env.DEFAULT_INPUT }}"

  Test2:
    if: ${{ needs.Environment.outputs.canRunJob }}
    needs: Environment
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo ${{ needs.Environment.outputs.canRunJob }}
