name: branch_name_push

on:
  push:

jobs:
  Environment:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Branch name "${GITHUB_REF#refs/heads/}

      - id: step2
        run: echo "Branch name "$GITHUB_REF_NAME

      - id: step3
        if: ${{ GITHUB_REF#refs/heads/ != 'develop' }}
        run: echo "This branch is not develop"
